### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by yilinxia** [yilinxia/arviz_dashboard#3]
# Overview
In order to speed up our implementation progress, we build this task list to record all features we plan to achieve. 

# Feature
- [ ] make the dashboard building process as a function `dash_builder`
- [ ] add one button and enable "show all pairwise comparison"
- [ ] add barplot: the summary of all observations
- [ ] y_axis range change for each plots
- [ ] checkbox: make y-axis range fixed across different pairwise plots
- [ ] check box:  (un) label the “extreme” points 
- [ ] intslider: threshold value 1/2/3
- [ ] dropdown: threshhold type (standard deviation etc)

# Issue
- [X] #1
- [ ] #2
